name: Label on Approval

on:
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write

jobs:
  add-label:
    name: Add integ test label
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Add run-integ-test label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr edit ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --add-label "run-integ-test"
